### ISSUE TITLE
Is Reload useful?

### ISSUE THREAD

**Issue by guekho64** [notepadqq/notepadqq#370] opened 2017-02-26 18:33 UTC
Another bug (Or feature un-request?).

This time, it affects text itself, or more specifically, text showing.

**How to reproduce**

* Write down something in Nqq, enough to trigger the scrollbar(s) (In case of multiple views)
* Right click any scrollbar
* Select "Reload"
* Enjoy chaos!

Is there any situation or specific utility for this "Reload" option? The first time I clicked it by accident, I freaked out as I saw all my code dissapearing in front of my eyes!

Fortunately, It's just kind of a visual bug, because, as far I didn't touch the "Save" button with my cleaned file, It kept all data.

As an extra, custom fonts dissapear too when using "Reload". Didn't notice any other issue...

P.S: Is #336 related to? Once again, I've confirmed #336 behavior, so maybe it's kind of the same?

**Comment by danieleds** [comment] 2017-02-26 20:38
Yep, duplicate of #336. That menu entry is something that shouldn't be there.

**Closed by danieleds** 2017-02-26 20:38 UTC
