### ISSUE TITLE
Editor Titlebar is only one row

### ISSUE THREAD

**Issue by kh-rony** [notepadqq/notepadqq#735] opened 2018-07-26 21:23 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x ] feature request
[ ] support request

**Current behavior**
Editor tab bar (title bar) is only one row. When many files are open, we have to switch left/right to access the desired tab for the file.

**Expected behavior**
It will be better if editor tab bar is not one row, can be multiple rows.

**Minimal reproduction of the problem with instructions**
https://user-images.githubusercontent.com/41761234/43289512-0b67bef6-914d-11e8-9bb1-914e0f1f4cb1.png


**Please tell us about your environment:**
Ubuntu 16.04 LTS, Notepadqq 1.4.8

**Comment by JuBan1** [comment] 2018-07-27 06:15
Will close this as it's a duplicate of #683. But FYI this won't happy anytime soon. We're using the native Qt Tab bar which doesn't support multi-rows. So we'd have to design one ourselves which is probably a fair bit of work.

**Closed by JuBan1** 2018-07-27 06:15 UTC
