### ISSUE TITLE
Make $HOME/Qt have precedence when loading

### ISSUE THREAD

**Issue by corelon** [notepadqq/notepadqq#146] opened 2015-08-26 21:58 UTC
I have installed Notepadqq from the PPA mentioned. It gave me the warning about Qt being < 5.3 (actually 5.2.1 running on Linux Mint 17.1)
I installed Qt 5.5 from the online installer without removing the already installed one and I still get the message.
I think $HOME/Qt and /opt/Qt as suggested in the popup should take precedence when loading the app.
I don't really know what I might break if I remove the repo Qt

**Comment by danieleds** [comment] 2015-08-27 08:55
They should already have precedence. The one installed from the repos has the lowest priority.
I think the problem is that Qt 5.5 is not recognized by the launch script yet. An update will come out soon.

**Comment by corelon** [comment] 2015-08-30 22:36
Hello.

funny thing happened. I reinstalled Qt with both 5.3 and 5.5 and now it is loading notepadqq with qt 5.5!!
That was weird, but I am not complaining as it is loading correctly.

**Comment by danieleds** [comment] 2015-09-03 14:17
Could be because you updated notepadqq with the latest version I had just released ;)
Closing!

**Closed by danieleds** 2015-09-03 14:17 UTC
