### ISSUE TITLE
Tab number is always increasing

### ISSUE THREAD

**Issue by erikdemarco** [notepadqq/notepadqq#871] opened 2019-04-28 16:37 UTC
When you start notepadqq tab name is 'new 1'
now open any file you like and close it, the tab number become 'new 2' it keeps increasing whenever we do open and close file. The real notepad++ is not like this. it keeps at 'new 1' and not increasing when we open close a file

**Comment by JuBan1** [comment] 2019-04-29 11:15
Duplicate of #630, will close this one.

**Closed by JuBan1** 2019-04-29 11:15 UTC
