### ISSUE TITLE
show end of line/show all characters not working

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [notepadqq/notepadqq#166] opened 2016-01-01 11:55 UTC
notepadqq                                             0.50.6-0~wily1

These characters can be quite useful in regex. It looks like the switch to show end of line/show all characters not working does not function. And these characters cannot be searched either with regex or special characters (except \t)

For replace feature, is there a way to use the value of the current match in "replace with" field? For instance, I want to prepend something to all matches.

**Comment by AbdElraoufSabri** [comment] 2016-07-14 19:11
The same issue here Notepadqq `v0.51.0` on Ubuntu `16.04`
Nothing showing after clicking the button of show all characters.

**Comment by darealshinji** [comment] 2016-07-14 20:02
Possible duplicate of https://github.com/notepadqq/notepadqq/issues/89

**Comment by danieleds** [comment] 2016-08-29 11:39
Fixed with #244

**Closed by danieleds** 2016-08-29 11:39 UTC
