### ISSUE TITLE
Preferences and tabs across sessions fix

### ISSUE THREAD

**Issue by itkfilelor** [notepadqq/notepadqq#387] opened 2017-03-10 22:28 UTC
Apologies, I didn't see anywhere else to put this as i am newer to github.  /blush
This is not actually a bug report, I see it was already addressed in [#345](https://github.com/notepadqq/notepadqq/issues/345). I did, however, find a temporary work around until a new version is released. It actually happened because i was getting a permissions error saving tabs across sessions, which i believe occurred because my first access to npqq was with sudo. 

What i did was: 
`sudo notepadqq /home/<user_name>/.config/Notepadqq/Notepadqq.ini`

while that is open:
`sudo chmod 666 /home/<user_name>/.config/Notepadqq/Notepadqq.ini`

edit your prefs i.e. colo schemes, tab size, etc.
Save, exit, and reopen everything should be as you left it. 

this should set the permissions back if you choose:
`sudo chmod 644 /home/<user_name>/.config/Notepadqq/Notepadqq.ini`

this will fix tabs permissions
`sudo chmod 666 /home/<user_name>/.config/Notepadqq/session.xml`

**Comment by danieleds** [comment] 2017-03-10 23:28
Thanks.

However, #345  is not related to the issue you're describing, which is probably related to the fact that you have ran notepadqq with sudo, thus altering the configuration permissions. This is not caused by notepadqq, but rather by an incorrect use of linux tools.

(the fix for #345 is already present in the last published version of notepadqq)

Closing, don't hesitate to add more info if you need.

**Closed by danieleds** 2017-03-10 23:28 UTC
