### ISSUE TITLE
Extensions Communication Protocol alpha only?

### ISSUE THREAD

**Issue by jayvdb** [notepadqq/notepadqq#597] opened 2018-04-07 04:23 UTC
https://github.com/notepadqq/notepadqq/wiki/Extensions-Communication-Protocol says it is only in the alpha branch, but https://github.com/notepadqq/notepadqq/wiki/How-to-write-an-extension-with-Node.js suggests it is now merged.

**Comment by JuBan1** [comment] 2018-04-07 19:50
The extension support mentioned in the 2nd link is merged. The other link is outdated.

I'm not familiar with coala but if I understand correctly you're only looking for a switch to open files in a new window? If so, use `--new-window` as an arg. We don't have support to open files at a specific line/column.

**Comment by jayvdb** [comment] 2018-04-08 09:32
I dont expect we're requiring a new window for the file.  If `--new-window` isnt used, I assume a new tab is used...?  As a user, I would be expecting coala to be opening a new tab of my editor, rather than a new window, as it might do this a few times during a code style fixup process on various files, and lots of new windows would annoy me.  But that is me, and that opinion is also not based on a working knowledge of how notepadqq works/is used.

Would be great if you can provide a CLI arg for specific line, but we can proceed without it for the current PR, and add it later after notepadqq has support or it.

**Comment by JuBan1** [comment] 2018-04-08 10:58
I see. Yes, if `--new-window` isn't used then a new tab will be opened or, if the file is already open in Nqq, the corresponding tab will be activated.

Regarding line/column arguments: I'll add support for a `-c` and `-l` switch and comment here again when its done. Shouldn't take long unless one of the other devs has any objections.

**Comment by JuBan1** [comment] 2018-04-09 15:09
`-l <line>` and `-c <column>` (or longer `--line` and `--column`) are in master now. 

But I thinking about it, it'll take quite some time until these changes reach the majority of the users.  Current Nqq versions will complain about these parameters and fail to launch. So for the time being it's probably best to not use them in coala unless you have a way of differentiating editor versions.

**Comment by JuBan1** [comment] 2018-04-09 15:11
I assume the issue is resolved (since that PR was merged). I'll close this one but feel free to reply or open another thread if there are any issues.

**Closed by JuBan1** 2018-04-09 15:11 UTC

**Comment by jayvdb** [comment] 2018-04-09 15:15
Yup; good call.  Ping us when you think most users will have the new version with line/col support and we'll update our config.  Much appreciated for helping us sort out the best optimal settings for the moment.
