### ISSUE TITLE
context menu sometimes shows only a "reload" entry

### ISSUE THREAD

**Issue by Jazoray** [notepadqq/notepadqq#336] opened 2017-01-06 23:28 UTC
this bug is rather inconsistent to reproduce, i couldn't find a single cause

steps to reproduce:

1. open a text file 

2. select a multiline block of text in that file.

3. right click on the selection

expected behavior:

the context menu containing cut, copy, paste, etc. is displayed

actual behavior:

a single item is displayed in the context menu: "Reload"

the position of the mouse cursor at the right click seems to affect the appearance of this reload context menu: when clicking on the first line of the selected text,  the context menu usually displays correctly. When clicking near the bottom end of the selected text, the context menu with "reload" is more likely to appear. 

if then the reload command is invoked, the content of the editor disappears as if the file was emptied in the meantime. even though it wasn't.

**Comment by eson57** [comment] 2017-01-07 05:21
I can confirm this behavior.

**Comment by JuBan1** [comment] 2017-01-07 16:23
I've seen this too. 

As far as I can see it's QWebPage's fault since it's job is to manage context-menu actions. That is only shows the Reload item in the context menu seems to be a bug. A possible solution would be to supply a custom context menu and simply add all the usual actions again (copy, paste, etc). 

But moving over to QtWebEngine is an item on the to-do list, and that might get rid of that bug as well.

![](http://i.imgur.com/42ZHbeU.png)

**Comment by gsawrk** [comment] 2017-01-20 07:29
I have seen this too

**Comment by danieleds** [comment] 2017-02-26 20:39
As noted in #370 , these are the steps to consistently reproduce it:

**How to reproduce**

* Write down something in Nqq, enough to trigger the scrollbar(s) (In case of multiple views)
* Right click any scrollbar
* Select "Reload"
* Enjoy chaos!

**Comment by lite1979** [comment] 2017-04-07 04:36
This just happened to me on Ubuntu 16.04. After closing and re-opening notepadqq, it's still happening. I cannot select the text with my mouse. I must use the keyboard.

**Comment by illucent** [comment] 2017-05-22 19:38
the same issue; sometimes but not always right click context menu is replaced by  single "reload";
i've tried it - "reload", it is actually "reset" for currently opened document

**Comment by rkok** [comment] 2017-10-29 15:29
Same here. I lost unsaved data a few times because of this issue.

**Comment by dustovich1** [comment] 2018-01-18 22:42
I have noticed this myself on Arch. I have noticed some specific behavior around it though:
- If it is a single line select it never happens
- If it is a dual line select it typically never happens
- If it is a three line select it most always happens.

Typically there is a weird scrolling up and down movement of the page when the mouse is right clicked before the Reload menu appears. If there is no scroll movement there is no chance the Reload menu appears. The more text that is selected the more the scrolling movement is accentuated. Once the scrolling movement goes over a certain threshold you get the Reload menu instead of the Cut/Copy/Paste menu. 

This isn't completely repeatable, as I just tried again and it wasn't doing it, but most of the time it happens.

Also when you click the reload button, as was stated above does a 'reset' which entails not just deleting all the data selected, but the entire document in memory with no possibility of recovery by undo. 

This is all for small text files for which there are no scroll bars present.

Hope this helps.

**Comment by farhank3389** [comment] 2018-01-23 14:22
Has this been fixed yet?

**Comment by tnilzon** [comment] 2018-01-28 07:08
This must be considered a BIG issue, it happens all the time. Please fix it as soon as possible, thanks.
/Tomas Nilzon, Sweden

**Comment by herbertxm** [comment] 2018-04-17 12:08
I have the same issue. =( When I select three lines or more, the right-click show the option Reload only. One or Two Lines it's ok.

**Closed** 2018-04-17 20:14 UTC
Labels: bug
