### ISSUE TITLE
memory leak...

### ISSUE THREAD

**Issue by erikdemarco** [notepadqq/notepadqq#873] opened 2019-04-28 19:18 UTC
memory usage comparison

firefox 20tabs (using 250mb ram)
notepadqq 3tabs (using 250mb ram)
notepad++ 3tabs (using 20mb ram) thats correct its not typo just 20mb. 10x smaller than notepadqq

**Comment by JuBan1** [comment] 2019-04-29 10:55
It's because of the Editor-component we're using. Unfortunately it's very RAM hungry because it's practically running a browser in which to display the text.

It annoys me too but it's nothing we can change unless we switch out the editor entirely. (For comparison, [nqq-ote](https://github.com/JuBan1/notepadqq#-notepadqq---opentextedit) only needs 20mb for 7 open tabs.)

Since it's not a bug per se, I'll close this.

**Closed by JuBan1** 2019-04-29 10:55 UTC
