### ISSUE TITLE
After the update "Segmentation fault" error

### ISSUE THREAD

**Issue by BloomCake** [notepadqq/notepadqq#593] opened 2018-04-04 10:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I can not start notepadqq anymore. I always get the following error: Segmentation fault (core dumped)
I updated notepadqq today about the Linux packages.

**Expected behavior**
Notepadqq should work normally?

**Minimal reproduction of the problem with instructions**
I just updated it.

**Please tell us about your environment:**
OS: Ubuntu 17.10
Version: Notepadqq 1.3.0

**Comment by danieleds** [comment] 2018-04-04 10:11
we're waiting for a fix to get published. Can you try to update again in a hour and check if that works?

**Comment by BloomCake** [comment] 2018-04-04 10:14
yes of course, thank you for your answer

**Comment by BloomCake** [comment] 2018-04-04 10:40
There was an update that I have installed (https://i.tlsh.pro/hDW9bI.png)
But the error is still the same:
$ notepadqq 
Segmentation fault (core dumped)

**Comment by danieleds** [comment] 2018-04-04 10:43
Quite strange. I've reverted to v1.2.0 to avoid more problems, and the new update should roll out soon.
This will give us some time to investigate the issue.

Thanks very much for your report and sorry for the inconvenience

**Comment by danieleds** [comment] 2018-04-04 10:44
@JuBan1 @Teklad are you guys able to replicate this on a development setup?

I can confirm the issue with apt packages. Snap packages don't seem to be affected.

**Comment by BloomCake** [comment] 2018-04-04 11:02
Thanks, it works again with version 1.2.0

**Comment by JuBan1** [comment] 2018-04-04 12:53
Can't replicate it on Ubuntu 16.04 when building from source. Is there a way to grab the 1.3.x apt package now that you've reverted to 1.2 @danieleds ?

**Comment by danieleds** [comment] 2018-04-04 12:57
they're not visible from launchpad anymore but still available at these addresses:

https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq-common_1.3.0-0~artful1_all.deb
https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq_1.3.0-0~artful1_amd64.deb

**Comment by JuBan1** [comment] 2018-04-04 13:08
These work fine too. No segfaults to be found.

**Comment by danieleds** [comment] 2018-04-04 13:11
Hmm, so the problem seems to be limited to Ubuntu 17.10. I need to try it on 18.04 just to see what happens.

By the way, what's the version of Qt that you used on 16.04?

**Comment by JuBan1** [comment] 2018-04-04 13:13
5.5.1 (the default). I'll give 17.10 a try later.

**Comment by danieleds** [comment] 2018-04-04 13:56
Runs great on a clean 18.04 install w/ default Qt 5.9.4

**Comment by JuBan1** [comment] 2018-04-04 14:08
Okay, turns out I had a VM with 17.10 around that I could use. I can confirm that source builds don't segfault while the .deb version does.

I ran the binary through gdb as best I could and it found the source of the segfault in `libQt5WebKit.so`. I double-checked that the WebKit version used to build the Artful apt package is the same as locally installed. I don't know why only the apt version segfaults.

**Comment by danieleds** [comment] 2018-04-04 14:11
Have you tried taking the notepadqq binary built from source and moving it to the path where the one installed with apt lives? Does it crash?

**Comment by JuBan1** [comment] 2018-04-04 14:25
The built `notepadqq-bin` works when replacing `/usr/lib/notepadqq..` with it.

And I can build and run it from source:

![img](https://i.imgur.com/iQUGghJ.png)

Although I somehow magicked my `lrelease` executable away in the process of debugging and now I can't compile properly anymore ~~

**Comment by danieleds** [comment] 2018-04-04 14:34
Might be related to #496

**Comment by danieleds** [comment] 2018-04-04 14:38
If that's the case, there might not be an easy fix. I'm tired of Qt and all its messy bugs.

I think we should really look forward to polish the webengine branch in order to throw qtwebkit away asap...

**Comment by sillybaboy** [comment] 2018-05-25 09:15
Same behaviour on Gentoo (v1.4.8) qtwebkit 5.9.1

**Comment by danieleds** [comment] 2019-10-03 20:40
Fixed by switching to QtWebEngine

**Closed by danieleds** 2019-10-03 20:40 UTC
