### ISSUE TITLE
randomly closing

### ISSUE THREAD

**Issue by ghost** [notepadqq/notepadqq#460] opened 2017-06-14 16:30 UTC
PLEASE FILL THE FOLLOWING INFORMATION

**I'm submitting a ...**  (check one with "x")

[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question

**Current behavior**
NotepadQQ randomly closes when editing C/C++(probably not limited to these formats) sources and headers.

**Expected behavior**
should not close itself

**Minimal reproduction of the problem with instructions**
its random and currently i cannot find a specific way to replicate it. it just happens like when deleting some characters or doing shortcut keys like ctrl+c ctrl+v

**Please tell us about your environment:**
Operating system : Antergos 
Qt version : 5.9.0 
Notepadqq version : notepadqq-git  1.0.1.r51.g354f70d-1 taken from AUR and compiled with notepadqq-git  1.0.1.r51.g354f70d-1
( iwas using the official community version before but that had the same issue)

**Comment by severach** [comment] 2017-06-14 19:52
[accessca.1.vb.crash.14560.test.zip](https://github.com/notepadqq/notepadqq/files/1075741/accessca.1.vb.crash.14560.test.zip)
I'm getting this too. The closing seems to happen when I press a key. Fortunately I've come up with a test file. Add a comma at the end of the last line in the file (14560).
````
$ pacman -Q linux notepadqq-git qt5-base                
linux 4.11.3-1
notepadqq-git 1.0.1.r51.g354f70d-1
qt5-base 5.9.0-2
````

**Comment by danieleds** [comment] 2017-06-14 20:49
Hi severarch, unfortunately I'm not able to reproduce the issue on a clean Ubuntu install with Qt 5.7.
It could be a bug introduced by more recent Qt versions.

**Comment by severach** [comment] 2017-06-14 23:38
Downgrading qt5-webkit 5.9 -> 5.8 has stopped the seg fault in the test file. notepadqq must have the same version to build but I can run with qt5-webkit at the lower version.

**Comment by severach** [comment] 2017-06-16 02:37
[Arch Linux Bug 54428](https://bugs.archlinux.org/task/54428)
Recompiling qt5-webkit 5.9 with gcc 6.3 also fixes it.

**Comment by The-Compiler** [comment] 2017-06-16 04:24
Also see https://github.com/annulen/webkit/issues/562 and https://bugs.webkit.org/show_bug.cgi?id=173407

**Comment by richardhendricks** [comment] 2018-04-19 20:51
I am seeing this issue as well.  It will work fine for quite a long time, multiple tabs etc.  Then suddenly it shuts down.  When I restart, it frequently shuts down again after deleting/changing a few characters.  Then it work fine for a long time again.

Xubuntu in a Virtualbox VM

Linux VirtualBox 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

~$ sudo apt-get install notepadqq
Reading package lists... Done
Building dependency tree       
Reading state information... Done
notepadqq is already the newest version (1.3.2-1~artful1).
The following packages were automatically installed and are no longer required:
  libodbc1 libosmesa6 libwine linux-headers-4.13.0-21
  linux-headers-4.13.0-21-generic linux-headers-4.13.0-36
  linux-headers-4.13.0-36-generic linux-image-4.13.0-21-generic
  linux-image-4.13.0-36-generic linux-image-extra-4.13.0-21-generic
  linux-image-extra-4.13.0-36-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 75 not upgraded.
~$

**Comment by danieleds** [comment] 2018-04-21 14:12
@richardhendricks try upgrading Qt to 5.10. This should fix the problem.

**Comment by richardhendricks** [comment] 2018-04-25 17:34
Thanks, I'll give the snap version a try.  It does complain about missing some icons, but appears to work
```Missing icon:  "go-previous"
Missing icon:  "go-next"
Missing icon:  "view-refresh"
Missing icon:  "document-open-recent"
Missing icon:  "application-exit"
Missing icon:  "edit-delete"
Missing icon:  "edit-select-all"
Missing icon:  "go-next"
Missing icon:  "go-previous"
Missing icon:  "go-jump"
Missing icon:  "view-fullscreen"
Missing icon:  "system-run"
Missing icon:  "window-new"
Missing icon:  "help-about"
```

**Comment by BradWebflex** [comment] 2019-04-11 00:57
I just installed the snap version on Fedora 29.. It crashes on load.   

I click the 'Report' button and that crashes. 

Notepadqq has been removed.

**Comment by danieleds** [comment] 2019-10-04 05:41
Fixed by switching to QtWebEngine

**Closed by danieleds** 2019-10-04 05:41 UTC
