### ISSUE TITLE
open file from remote sshfs take ages

### ISSUE THREAD

**Issue by bobbisanchez** [notepadqq/notepadqq#341] opened 2017-01-24 19:25 UTC
Hi,

i run the latest Version of Notepadqq (0.53.0-71-g8116744), 
i have an remote storeage mounted with sshfs, then i open DoubleCommander, traveling to the desired directory and pressing F4 to open the file with an external Editor, in this case Notepadqq, but it takes at least 20 SECONDS !!!!! to open the document in Notepaddqq. Thats really disgusting if you have many files to edit and waiting at least 20 Seconds per file, till the document is opened. With other Editors, i have not seen such a big waiting delay. Thanks

reproduce:
1) mount the remote storeage with sshfs
2) open DoubleCommander(latest Version: beta 0.7.7) and traveling into the desired directory, choose your file to open, Press F4 and wait 20 Seconds till Notepadqq has succesfull opened the file.

My thread in the DoubleCommander Forum.
http://doublecmd.sourceforge.net/forum/viewtopic.php?f=5&t=3326&hilit=sshfs+ages

**Comment by guekho64** [comment] 2017-01-26 19:20
After reading this and your post on DoubleCMD, I've got some questions for you, so maybe we'll clarify this situation:

Note: I'm not familiar with "sshfs"

+ Have you tried to open the external file from command-line?
~ Something like _"/path/to/nqq" "/path/to/file"_

If it delays opening the file, then it's not DoubleCMD's fault, because, as DCMD's site admin says, it should only open file with the selected editor. Nothing else.

Now, IF IT DOESN'T DELAY opening the file, then DCMD could be doing something else. Maybe he wrote a _'sleep'_ command inintentionally?

**Comment by bobbisanchez** [comment] 2017-01-27 17:11
Hi guehko64,

the files i open local on my LinuxBox with notepadqq, on the remote machine, is mounted with sshfs, the filesize is around from 0KB till max 50KB, the files are only small shells scripts, no other then me has access to the files and they are not opened in the background or executed, access rights are ok! I tried with many other editors and i dont have any problem to open the files as above described, I have only a big delay in combination to open file inside from Double Commander with Notepadqq, this problem do not happend before with any other editor. The Connection between me and the server has mostly no big delays, the server is also not busy or the connection has problems, cause other editors hasnt the big delay.

What i noticed is, if i run wireshark to inspect the connection packets, i can see when i try to open a file from the sshfs folder (DCMD+external Editor Notepadqq(F4)), 1200 packets, small packets are exchanged, then the exchange stops and the big delay is over and notepadqq come on the screen.

Anything forgetten to tell ?
regards

**Comment by danieleds** [comment] 2017-01-27 18:12
Hi,
I've tried to reproduce the problem without any success.
Can you provide more details about your setup and maybe an example file?

Thanks

**Comment by guekho64** [comment] 2017-01-27 19:49
Well, that means that I'm right. Everything I wrote above it's based on what I thought 'sshfs' was, and it seems to be correct from what you say...

As @danieleds says, try providing more details about your problem, so we can reproduce it to find a solution for it!

**Comment by bobbisanchez** [comment] 2017-01-27 21:29
hi danieleds,

#sshfs mount command
sshfs username@remotehost:/ /media/sshfs/ -p12345 -o Identityfile=id_rsa -o ServerAliveInterval=15,auto_cache,reconnect -o Compression=no -o Ciphers=arcfour

I have noticed, running DCMD, goto the directory where the file is located for editing, having an sshfs connection and i restart the sshd server on the remote machine, and just execute the sshfs command above again to get sshfs mounted again, doing a refresh of the folder/files (the green arrow on the toolbar of DCMD,top left icon) inside DCMD and pressing F4 to open a file, notepadqq opens the file immediately, then when i close notepadqq, goto another directory from the mounted sshfs folder and open another file, then i have again a big delay. 

#server:
Linux Tinycore 3.16.6 Kernel SMP x86_64 GNU/Linux
OpenSSH_6.4p1, OpenSSL 1.0.2d
#client: 
4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux
Double Commander beta 0.7.7
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
Notepadqq (0.53.0-71-g8116744)

*Example file attached, thats the kind of files id like to edit with npqq
Thanks
What also do you need to know ?

**Comment by bobbisanchez** [comment] 2017-01-27 21:30
hi danieleds,

#sshfs mount command
sshfs username@remotehost:/ /media/sshfs/ -p12345 -o Identityfile=id_rsa -o ServerAliveInterval=15,auto_cache,reconnect -o Compression=no -o Ciphers=arcfour

I have noticed, running DCMD, goto the directory where the file is located for editing, having an sshfs connection and i restart the sshd server on the remote machine, and just execute the sshfs command above again to get sshfs mounted again, doing a refresh of the folder/files (the green arrow on the toolbar of DCMD,top left icon) inside DCMD and pressing F4 to open a file, notepadqq opens the file immediately, then when i close notepadqq, goto another directory from the mounted sshfs folder and open another file, then i have again a big delay. 

#server:
Linux Tinycore 3.16.6 Kernel SMP x86_64 GNU/Linux
OpenSSH_6.4p1, OpenSSL 1.0.2d
#client: 
4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux
Double Commander beta 0.7.7
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
Notepadqq (0.53.0-71-g8116744)

*Example file attached, thats the kind of files id like to edit with npqq
Thanks
What also do you need to know ?

**Comment by bobbisanchez** [comment] 2017-01-27 21:33
[arraytest.zip](https://github.com/notepadqq/notepadqq/files/736305/arraytest.zip)
[arraytest.zip](https://github.com/notepadqq/notepadqq/files/736306/arraytest.zip)

hi danieleds,

#sshfs mount command
sshfs username@remotehost:/ /media/sshfs/ -p12345 -o Identityfile=id_rsa -o ServerAliveInterval=15,auto_cache,reconnect -o Compression=no -o Ciphers=arcfour

I have noticed, running DCMD, goto the directory where the file is located for editing, having an sshfs connection and i restart the sshd server on the remote machine, and just execute the sshfs command above again to get sshfs mounted again, doing a refresh of the folder/files (the green arrow on the toolbar of DCMD,top left icon) inside DCMD and pressing F4 to open a file, notepadqq opens the file immediately, then when i close notepadqq, goto another directory from the mounted sshfs folder and open another file, then i have again a big delay. 

#server:
Linux Tinycore 3.16.6 Kernel SMP x86_64 GNU/Linux
OpenSSH_6.4p1, OpenSSL 1.0.2d
#client: 
4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux
Double Commander beta 0.7.7
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
Notepadqq (0.53.0-71-g8116744)

*Example file attached, thats the kind of files id like to edit with npqq
Thanks
What also do you need to know ?

**Comment by guekho64** [comment] 2017-01-28 04:55
I've been thinking a while about this problem, and, based on what you've said, the problem could be in SSHFS.

You did mention that some kind of packet exchange was made before opening the file with Notepadqq.
Now, you're saying that if 'you goto the directory where the file is located for editing, having an sshfs connection and you restart the sshd server on the remote machine, and just execute the sshfs command above again to get sshfs mounted again, doing a refresh of the folder/files (the green arrow on the toolbar of DCMD,top left icon) inside DCMD and pressing F4 to open a file, notepadqq opens the file immediately', then something is done before actually opening the file, and abruptly restarting the server could cause that "pre-process" to be omited/killed

Could it be some kind of "Autenthication"? 
Could It be auth to the file itself or to your user?

Anyways, if it's an authentication process, and you can omit/kill it, then you could have discovered a bug on your secutiry framework managing your ssh connection!

If it's not, then I can't realize what kind of process its executed before opening the file, but I'm pretty sure something is done after you try to open the file with DCMD...

**Comment by Teklad** [comment] 2017-01-28 05:23
You could try fiddling with sshfs options... something like this:
sshfs USERNAME@HOSTNAME_OR_IP:/remote/path /local/mount/point 
-oauto_cache,reconnect,Ciphers=arcfour

This isn't a fix-all... but it should help with the latency issues a bit 
at least.

**Comment by bobbisanchez** [comment] 2017-01-29 12:28
ok, after some more research i found out, when i start notepadqq directly from "/usr/lib/notepadqq/notepadqq-bin", the issue with the 20Seconds waiting delay is gone,

I mean, normally i use "/usr/bin/notepadqq" to start notepadqq, but with this i have 20Seconds delay at least. 
Using "/usr/lib/notepadqq/notepadqq-bin" all works perfect .....
Thanks

**Comment by danieleds** [comment] 2017-01-31 14:50
That's quite strange, "/usr/bin/notepadqq" is just a simple script which executes notepadqq-bin.
Anyway, I'm closing this as it doesn't seem to be related to Notepadqq but rather to some other problem.

**Closed by danieleds** 2017-01-31 14:50 UTC

**Comment by RobTranquillo** [comment] 2017-01-31 16:41
I have the same proble since couple of months and now i just found this thread, i am vote for keep the issue open! Because its realy annoying maybe the problem of DComander. 

I use debian 8 (64bit) and geany as external editor (path: /usr/local/bin/geany) and with it it needs minimum 10Seconds to open any textfile on an sshfs mounted directory. The DoubleComander intenal Editor opens any file just in time. And open a file via bash with gany works also without any delay. So it seems to me not to be a sshfs problem.

One notice: DCommander shows in the message window a empty the working directory as a last antry on the comand line, like this:

Result external: Result=Success! / Filename=/usr/local/bin/geany / Param=/media/externalsrv/cmssystem/api.php / WorkDir=

**Comment by danieleds** [comment] 2017-01-31 18:30
For the sake of completeness, I'd like to quote a reply added by a user some hours ago (the message has been deleted a few minutes later because probably the author realized that this is not the repository of DCommander)

> I have the same proble since couple of months and now i just found this thread, i am vote for keep the issue open! Because its realy annoying maybe the problem of DoubleComander.
> I use debian 8 (64bit) and geany as external editor (path: /usr/local/bin/geany) and with it it needs minimum 10Seconds to open any textfile on an sshfs mounted directory. The DoubleComander intenal Editor opens any file just in time. And open a file via bash with gany works also without any delay.

So it looks like the issue happens with Geany too.
