### ISSUE TITLE
Error saving session

### ISSUE THREAD

**Issue by vertigo220** [notepadqq/notepadqq#577] opened 2018-03-15 19:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting (done)
```

**Current behavior**

I'm not even sure how it happened. I had multiple instances of Nqq open, and the only thing I can think of is that some were open as root (to edit files owned by root) and some were open as me, the user. But when I tried to close a Nqq window, I got the error "Error trying to write to "/home/keith/.config/Notepadqq/tabCache/monitrc.1006151010 -- Permission denied." Considering this is a directory under my (user) home directory, I wouldn't expect myself or root to have any problem writing to it. I did the "Retry as root" but that didn't work. I went to the directory and (IIRC) couldn't write anything in it except as root. I did ls -la and this was the result:

total 20
drwxr-xr-x 2 root  root  4096 Mar  7 12:04 .
drwxrwxr-x 3 keith keith 4096 Mar  6 15:24 ..
-rw-r--r-- 1 root  root   970 Mar  6 15:24 monitrc.794864509
-rw-r--r-- 1 root  root   727 Mar  6 15:24 system-status.1302088411
-rw-r--r-- 1 root  root     8 Mar  7 12:04 test.test

I then tried "sudo chown keith. *" but that didn't seem to change anything.

**Expected behavior**

I'm not really sure if this is a bug or just an unfortunate case of getting things all twisted up with permissions, but it seems that a) it shouldn't be possible to get into that position and b) "Retry as root" should have worked. In any event, I was unable to save my session. Not exactly a huge deal, but irritating, and if I'd had a bunch of files open it could have been problematic.

**Minimal reproduction of the problem with instructions**

As mentioned, I'm not even sure how I got to that point. I just know I had around 4 different Nqq windows open, some ran from the terminal, some (I think) run by launching from the panel and/or opening a file, some as root, some as user/me. I'll admit that being new to Linux I don't fully understand the intricacies of permissions and the limitations imposed by them. I just know that in many, many years of using N++ in Windows I've _never_ had a problem, and in just a few weeks of use in Linux this happened.

**Please tell us about your environment:**

Mint 18.3
Qt 5.5.1
Nqq 1.2.0

**Comment by JuBan1** [comment] 2018-03-15 20:17
I'm impressed, to be honest. I didn't even know you could run multiple instances of Nqq that way! But it turns out you can.

First things first: you should try to avoid running programs as root if you can. And as it happens, Notepadqq has the ability to edit root-owned files. You have to have either `gksu` or `kdesu` installed. If you do and you attempt to save a root-owned file you'll get a new option to save as root:

![img](https://i.imgur.com/Q4Xi7w8.png)

(Of course we don't tell anybody that because our documentation is pretty bad in places.)

Only downside is you'll have to re-enter your password on every save. But it'll save you from potential issues like that.

About the actual issue: it seems the root Notepadqq wrote those session files (as root, naturally) and the non-root Notepadqq attempted to remove them when trying to save its own session. Since it couldn't, it threw an error. 

Notepadqq's session system was never intended to deal with two running instances at the same time (that's why running `notepadqq` in terminal will immediately terminate if Nqq is already running). I'm a bit surprised that root-Nqq will still attempt to write into your `$HOME/.config/Notepadqq` directory; it should generally choose `/root/.config/Notepadqq` but I guess running both at the same time messed something up.

If you still have trouble saving sessions, you'll probably have to remove the `tabCache` folder and the `sessions.xml` file in your `$HOME/.config/Notepadqq`.

@danieleds I can go hunt down this bug but I think we should rather just prohibit running Notepadqq as root (like many other applications do). Perhaps even better, add a `--allow-root` switch that needs to be passed if you want to allow Nqq root. That way, users can choose to run root if they really want to.

**Comment by danieleds** [comment] 2018-03-15 21:33
> I can go hunt down this bug but I think we should rather just prohibit running Notepadqq as root (like many other applications do). Perhaps even better, add a --allow-root switch that needs to be passed if you want to allow Nqq root. That way, users can choose to run root if they really want to.

I don't think we should prohibit that, I've never heard of any text editor doing that. I would find that strange. But you can change my mind.

I believe the problem is just that @vertigo220 ran the application using sudo instead of the correct equivalent. From the [Ubuntu wiki](https://help.ubuntu.com/community/RootSudo#Graphical_sudo):

> You should never use normal sudo to start graphical applications as root. You should use gksudo (kdesudo on Kubuntu) to run such programs. gksudo sets HOME=~root, and copies .Xauthority to a tmp directory. This prevents files in your home directory becoming owned by root. (AFAICT, this is all that's special about the environment of the started process with gksudo vs. sudo).

**Comment by JuBan1** [comment] 2018-03-15 21:48
Trying to run Kate as sudo will leave you with

> Executing Kate as root is not possible.

Martin Gräßling, the maintainer of KDE's KWin, once wrote a [blog entry](https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/) about it, although it's mostly focused about the security aspect. There's also the fact that if a program malfunctions in some way it can do the most damage if run as root. Then there's also the chance of (new) users accidentally breaking something by mishandling sudo, as has happened here. And a minor issue: running as sudo doesn't load your usual platform theme/config file so you'll lose all settings and visuals.

Though I do recognize the convenience of being able to run as sudo, which is why I'd be in favor of hiding it behind a commandline flag like `--allow-sudo`.

**Comment by danieleds** [comment] 2018-03-15 21:50
> But you can change my mind.

You did :)

**Comment by vertigo220** [comment] 2018-03-15 23:24
@JuBan1 

Thanks for the explanation. Glad I could break it to give you guys something to fix. : P

> First things first: you should try to avoid running programs as root if you can.

Unfortunately, I thought I had to, since I was editing root owned files. Also, I don't necessarily agree with the whole philosophy of avoiding root usage, and actually think it's better to run as root while keeping certain programs contained by running them as a user (e.g. browsers), which protects your files whereas the standard way of doing things only protects the relatively unimportant system files (the concept behind Puppy et al). That all said, that's still good info to know about gksu.

@danieleds 

Ironically, I had previously looked into the difference between sudo and gksudo and, aside from the obvious of prompting for the password in the terminal vs a GUI pop-up, didn't find one. Yet now, this is the second time today I'm reading about the difference you mentioned. Go figure.

**Comment by JuBan1** [comment] 2018-03-17 17:37
The `--allow-sudo` patch is now merged so I'll close this. I'll chalk that permission issue up to "things you shouldn't do" :)

**Closed** 2018-03-17 17:37 UTC
