### ISSUE TITLE
Segmentation fault in Ubuntu 17.10

### ISSUE THREAD

**Issue by mateusrachid** [notepadqq/notepadqq#496] opened 2017-10-24 21:44 UTC
I'm submitting a bug report.

**Current behavior**
Notepadqq segfaults when I try to edit text in some ways (typing in overwrite mode, removing indentation with shift+tab, etc) in line containing specific text.

**Expected behavior**
Not crashing at all

**Minimal reproduction of the problem with instructions**
I can reproduce this on many very specific procedures. Here goes one of them:

1. Open a new document. Paste this line (45 letters a)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2. Put cursor at the start of the line, press Insert to change to OVERWRITE mode.
3. Press key B repeatedly, effectively overwriting all a's with b's.

Notepadqq crashes with segmentation fault before you can finish overwriting the whole line in step 3.

Notes:
--> It doesn't occur when you type all 45 a's in step 1 instead of pasting.
--> It does occur if you open a file containing this line in step 1, instead of pasting.

Notepadqq was crashing on me frequently and apparently at random after I updated my system, then I figured out some specific procedures that would make it crash.

**Please tell us about your environment:**
Ubuntu 17.10 (artful) fully updated (as of 24th Oct)
Notepadqq 1.2.0 from official repo (notepadqq amd64 1.2.0-1~artful1)
Qt 5.9 (using libqt5webkit5=5.9.1+dfsg-5ubuntu1)

Qt was updated from 5.7 to 5.9 when upgrading from Ubuntu 17.04 to 17.10. Unfortunately it seems to be impossible to downgrade Qt to test if it solves the problem without breaking the system.

**Comment by danieleds** [comment] 2017-11-06 16:29
Thanks for the clear bug report. Confirmed.

**Comment by skyide** [comment] 2017-11-11 23:07
I have exactly the same issue and I believe I found what the problem is:

```
Thread 1 "notepadqq-bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff65d18cf in JSC::JSRopeString::resolveRope(JSC::ExecState*) const () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
```
`lrwxrwxrwx 1 root root       21 Sep 25 23:26 /usr/lib/x86_64-linux-gnu/libQt5WebKit.so -> libQt5WebKit.so.5.9.1
`
However this does not happen with the AppImage version because it would be using its own version. Looks like an issue with libQt5WebKit.so.5.9.1.

**Comment by Johnreidsilver** [comment] 2018-01-02 23:22
Same situation here, worked fine in ubuntu 17.04, while a fresh install of 17.10 crashes while editing for example the digit "6" on the number 16 in the list below:
[,c(11,12,13,14,15,16,17,18,19,20,21,22)]
Copy paste to notepadqq and try to delete 6, instant crash.

**Comment by mary-kate** [comment] 2018-01-04 13:13
Confirming this on Ubuntu MATE 17.10 with a fresh install of Notepadqq -- tested out @Johnreidsilver's simplest test case and indeed, Notepadqq crashes every time. As per @skyide's comment, the AppImage version is unaffected so I'm using that now.

**Comment by JuBan1** [comment] 2018-01-04 15:49
Nqq's a bit of a mess right now, what with QWebKit slowly being phased out.

I'll update the repo's README to notify users of this issue and suggest installing the AppImage instead. The long-term fix would be to get rid of QWebKit entirely but that won't happen anytime soon as nobody's working on it.

**Comment by skyide** [comment] 2018-02-02 09:26
I haven't really messed with Nqq's source code except when I experimented with an AppImage so let me just ask, is QWebKit a required component or can we just recompile Qt without webkit and then recompile NQQ? That shouldn't be too much trouble.

**Comment by Fullmetal5** [comment] 2018-02-14 22:05
This crash was really annoying me and since it hasn't been fixed yet here is a (probably bad) workaround.

sudo apt build-dep libqt5webkit5
sudo apt install build-essential fakeroot devscripts
mkdir src; cd src
apt source libqt5webkit5
cd qtwebkit-opensource-src-5.9.1+dfsg
wget "https://gist.githubusercontent.com/Fullmetal5/ecc2ac95b182a24aacbc3080a8345440/raw/2f63425505dcd6c125bb903453bf9d2a99082109/notepadqqFix.diff"
patch -p1 < notepadqqFix.diff
debchange -i #(maybe omit this so future updates aren't skipped, just rebuild after)
debuild -us -uc -i -I
sudo debi

**Comment by danieleds** [comment] 2019-10-03 20:40
Fixed by switching to QtWebEngine

**Closed by danieleds** 2019-10-03 20:40 UTC
Labels: bug
