### ISSUE TITLE
Find And Replace not performing replacement with special characters

### ISSUE THREAD

**Issue by Arffeh** [notepadqq/notepadqq#451] opened 2017-05-21 04:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Find and replace does not substitute in special characters correctly

**Expected behavior**
I would expect being able to replace with special characters, in a similar manner as N++

**Minimal reproduction of the problem with instructions**
Currently, if I hit Ctrl-H and
Find: ,
Replace: \n
Advanced -> Regex

In N++ it correctly replaces all commas with newlines.
Nqq currently replaces commas with an 'n' and calls it a day.

**Please tell us about your environment:**

Nqq version: v1.0.1, commit #b58bc5e (Latest as of writing)
OS: Debian 8
Qt: 5.7.1

**Comment by JuBan1** [comment] 2017-05-21 11:31
Duplicate of #60.

CodeMirror, the underlying library we use as a text editor, doesn't match across newlines. We've got plans to move away from it but that likely won't happen any time soon.

Good news is, #446 allows you to use the new advanced search tool for that. Hopefully we'll get the changes merged into master soon.

**Comment by ericjs** [comment] 2017-05-25 21:13
It's not a duplicate, replacing something _with_ a newline is not the same functionality as matching _across_ lines. 

This is a very important feature. I've used it many different editors, and its a key technique when you need to change the file format of something. Or for example taking a directory listing output and turning each line into several bash commands. That kind of thing.

**Comment by JuBan1** [comment] 2017-05-26 14:05
My bad, I misread it as replacing a newline with something else.

Yep, that's a bug. The new search panel can do this just fine. Once it's merged I think I'll also tackle the "simple" search to work the same way.

**Comment by Arffeh** [comment] 2017-05-26 14:11
Thank you. :)

**Comment by JuBan1** [comment] 2018-01-23 17:52
Fixed by de15c09 using the new search and replace tool.

**Closed by JuBan1** 2018-01-23 17:52 UTC

**Comment by sergeda** [comment] 2018-08-15 09:32
I am trying to replace text with tabs using \t without luck. Using version 1.4.8. Should this  work?

**Comment by JuBan1** [comment] 2018-08-15 13:49
@sergeda I just tested it and it works. If you're using the normal search&replace tool you need to select `Show Advanced Options` and tick "Search with special characters". Otherwise the search tool will look for "\t" instead of tabs.

https://i.imgur.com/RBeVgCt.png

**Comment by sergeda** [comment] 2018-08-16 00:45
@JuBan1 I'm not talking about searching for \t but use it in replacement text. Say I want to replace all spaces with tabs. I will enable regex search and put \s in the "Find" field and \t in the "Replace to" field.

**Comment by JuBan1** [comment] 2018-08-16 11:43
That works for me as well. [See here](https://gfycat.com/MenacingImportantBluetonguelizard).

**Comment by sergeda** [comment] 2018-08-20 08:28
@JuBan1 I've played with replace window and replacement with special characters works only if I select "Search with special characters" and doesn't work with other types of search. I've verified that I have version 1.4.8

**Comment by JuBan1** [comment] 2018-08-29 08:05
@sergeda You're right about that. In the meantime until this is fixed you can either use the "Search with special characters" or, if you need regex, use the advanced search panel.
