### ISSUE TITLE
AppImage Request

### ISSUE THREAD

**Issue by ElectricPrism** [notepadqq/notepadqq#308] opened 2016-11-01 02:01 UTC
Some users report that they would like to try Notepadqq but it's not currently available on their system.

How hard would it be to have a build bot create a Notepadqq AppImage to increase the user base? (Other apps like Krita are already doing this with great success)

http://appimage.org

**Comment by probonopd** [comment] 2016-11-01 20:48
Shouldn't be hard at all, especially given that this project is already building on Travis CI. See [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) and especially the [Travis CI examples](https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt) linked there. Basically `linuxdeployqt -appimage` can do it automatically for you.

**Comment by danieleds** [comment] 2016-11-03 19:31
If someone wants to try working on this, I'm fully supporting the idea of having official Notepadqq AppImages.

**Comment by probonopd** [comment] 2016-11-03 20:13
@danieleds I tried to convert the deb from the trusty ppa to an AppImage but I get

> Install a newer Qt version (≥ 5.3) from the official repositories of your distribution.

It would be nice if the deb in the trusty ppa would be packaged in a way that uses https://launchpad.net/~beineri/+archive/ubuntu/opt-qt57-trusty, then it would also be easier to convert the deb from the trusty ppa to an AppImage using this simple `.yml` file and the meta [Recipe](https://raw.githubusercontent.com/probonopd/AppImages/master/recipes/meta/Recipe):

```
app: Notepadqq

ingredients:
  dist: trusty
  sources: 
    - deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe
  ppas:
    - notepadqq-team/notepadqq
    - beineri/opt-qt57-trusty
```

**Comment by danieleds** [comment] 2016-11-03 21:13
@probonopd why not Xenial instead of Trusty? Just asking

**Comment by probonopd** [comment] 2016-11-04 06:57
Older ingredients in the AppImage run on newer target systems, but not the other way around. Hence I recommend to use ingredients compiled on the oldest system possible.

**Comment by darealshinji** [comment] 2016-11-15 20:15
I built this AppImage: https://drive.google.com/file/d/0BxClEVSW8QykaG9VTWhlX1NOeU0/view?usp=sharing

I had some trouble with linuxdeployqt, so instead I've compiled static Qt libraries (qt-everywhere-opensource-src-5.6.2 + qtwebkit-opensource-src-5.7.0), build nqq against it, manually linked in some other libs statically and used the `functions.sh` script to build the AppImage. All done in an Ubuntu 14.04 chroot. Seems to work so far for me in Ubuntu 16.04. Not sure about other distros.

**Comment by danieleds** [comment] 2016-11-15 23:00
Works for me too on Ubuntu 16.10.
And the file size is quite small, just 33MB! Not bad at all

**Comment by probonopd** [comment] 2016-11-16 05:20
> I had some trouble with linuxdeployqt

Please report about it in https://github.com/probonopd/linuxdeployqt/issues/ since linuxdeployqt is still relatively new and we are looking to make it more robust. Congrats on the AppImage build though :-)

**Comment by guekho64** [comment] 2016-11-16 05:36
Works just fine!

Just a question:

Why does Nqq displays some "different" icons that usual:

[![Captura de pantalla de 2016-11-15 23:36:03.png](https://s12.postimg.org/gpddk5wjh/Captura_de_pantalla_de_2016_11_15_23_36_03.png)](https://postimg.org/image/6s2cr3oxl/)

**Comment by danieleds** [comment] 2016-11-16 11:08
@guekho64 I confirm the problem on 16.10 but I think the issue is with Qt 5.7 itself, not with the appimage.

Lately, Qt is creating new regressions at each new release.....

**Comment by danieleds** [comment] 2016-11-16 11:13
@darealshinji do you think we could automate the process? :)

**Comment by darealshinji** [comment] 2016-11-16 15:10
I'm currently working on a script that automates the process. But first I will make a pull request that adds missing include directives that I need to build nqq against Qt 5.6.2. By the way I would use Qt 5.7 but the build system is somehow borked for me.

**Comment by darealshinji** [comment] 2016-11-16 23:11
Here's the script which will automatically build Qt, QtWebkit and then the notepadqq AppImage: https://gist.github.com/darealshinji/86e06a433966b7663cf8377bde79670b

Here's the AppImage: https://drive.google.com/file/d/0BxClEVSW8QykY1NxOXM2Qi1pdTQ/view?usp=sharing

**Comment by danieleds** [comment] 2016-11-17 11:20
Perfect! :)
I want to find a way to insert it cleanly in the travis workflow, so that we can automate deployments.

**Comment by darealshinji** [comment] 2016-11-17 11:29
Uploading pre-compiled Qt libraries to travis may greatly improve the build speed.

**Comment by darealshinji** [comment] 2016-11-17 15:31
I've updated the script: https://gist.github.com/darealshinji/86e06a433966b7663cf8377bde79670b

**Comment by guekho64** [comment] 2016-11-20 05:20
Incredibly, it works in Debian 7, with some tweaks (You must run the Appimage as root to let Debian mount the AppImage & force Debian to upgrade libc6-dev to 2.15 or greeter. For this, you can add Jessie's repo temporarily, upgrade libc6-dev and delete repo to avoid any kind of damage/corruption to your Derbian 7 box)

This shows me that AppImages could be a great way to "force run" apps that usually would be impossible/very difficult to install using the "normal" way.

If you try to install Nqq using apt, even trying to force upgrade the strictly necessary packages that Nqq needs, it'll totally break your OS (It'll install a ton of critical packages that could cause weird behavior...)

I hope this "branch" of Nqq packaging will continue alive! :D

[![Screenshot from 2016-11-20 05:09:28.png](https://s15.postimg.org/772h0ncrf/Screenshot_from_2016_11_20_05_09_28.png)](https://postimg.org/image/9oe87wwnr/)

**Comment by darealshinji** [comment] 2016-11-20 05:37
@guekho64 Wow, that sounds pretty cool. By the way to mount the AppImage you must be a member of the "fuse" group or whatever that group is called. Add your user account to that group and root rights shouldn't be necessary. As for glibc, you could try to build a newer version from source, install it in a separate prefix and use the dynamic linker from there to start the AppImage. I don't know if this works with AppImages, but it normally works with regular apps.

**Comment by guekho64** [comment] 2016-11-20 07:34
Well, I'll see if adding my user to the "fuse" group helps me to mount the AppImage without being "root". 

You know, as root everything is possible, xD (`rm -rf "/"`?)

I'll try to build glibc from source as well, but as long this works, I think i'll postpone that.

Thanks!

**Comment by probonopd** [comment] 2016-11-20 09:55
@guekho64 

> force Debian to upgrade libc6-dev to 2.15 or greeter

Why does a text editor need a `-dev` package at runtime?

**Comment by danieleds** [comment] 2016-11-20 11:37
For me, apt fails with
```
After this operation, 185 MB of additional disk space will be used.
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main gir1.2-gdkpixbuf-2.0 amd64 2.30.7-0ubuntu1.2
  404  Not Found [IP: 91.189.88.152 80]
Err http://security.ubuntu.com/ubuntu/ trusty-security/main gir1.2-gdkpixbuf-2.0 amd64 2.30.7-0ubuntu1.2
  404  Not Found [IP: 91.189.88.161 80]
Err http://security.ubuntu.com/ubuntu/ trusty-security/main libgdk-pixbuf2.0-dev amd64 2.30.7-0ubuntu1.2
  404  Not Found [IP: 91.189.88.161 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gdk-pixbuf/gir1.2-gdkpixbuf-2.0_2.30.7-0ubuntu1.2_amd64.deb  404  Not Found [IP: 91.189.88.161 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gdk-pixbuf/libgdk-pixbuf2.0-dev_2.30.7-0ubuntu1.2_amd64.deb  404  Not Found [IP: 91.189.88.161 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by darealshinji** [comment] 2016-11-20 20:27
@danieleds I assume you're trying to run this in chroot or travis? Do you have the repositories trusty-updates and trusty-security enabled? Those packages there **are** available in Ubuntu 14.04, so it's not a problem with my script.

**Comment by guekho64** [comment] 2016-11-21 04:02
@probonopd

As I've alredy seen in Synaptic, maybe you're right. 

The package "`libc6-dev`" depends on "`libc6`", so maybe that's why I thought it was the "main" package, when installing the "normal" package should be enough

**Comment by danieleds** [comment] 2016-11-21 08:47
> I assume you're trying to run this in chroot or travis?

@darealshinji I'm running it from a fresh trusty64 vagrant environment, with trusty-updates and trusty-security enabled. Anyway, I tried again and now it works... Looks like it was a temporary problem on my end.

**Comment by probonopd** [comment] 2016-11-21 09:24
@danieleds it is a known limitation of GNU userland binary compatibility that you need to compile with the same or an older glibc than you intend to run on. So in practice this means "use the oldest build system your software still builds on", for maximum binary compatibility with more-than-the-latest distros. Bundling glibc inside the AppImage is not recommended for various reasons and can lead to breakage if done improperly.

**Comment by darealshinji** [comment] 2016-12-20 12:50
I've uploaded a static build of Qt 5 to Github: https://github.com/darealshinji/qt5-static/releases
You can try to use it to build the AppImage. Extract the tarball into `/var/tmp/` and use it from there.

**Comment by skyide** [comment] 2017-01-01 00:41
I've successfully built Notepadqq with QtCreator and also successfully built an AppImage for it however when running the AppImage, I got `"Can't open file: /tmp/.mount_7Ck36V/../../share/notepadqq/editor/index.html"`. 

Having settings in /tmp is a terrible idea so I went through the code and I modified `QString Notepadqq::appDataPath(QString fileName)` to make it look in `$HOME/.notepadqq/`instead for the settings and now the error message looks like this: 

 `"Can't open file: /home/skyide/.notepadqq/editor/index.html. To fix this, download: http://example.com/notepadqq_settings.zip and extract the contents to: /home/skyide/.notepadqq/"` but I also added a graphical message box in main.cpp using QMessageBox right below line 109 to make the error a bit more friendly rather then being silent with no activity. So now when the Notepadqq is started, if the settings cannot be found, it displays a graphical message box on the screen.

Once I copy editor, extension_tools and translations to `$HOME/.notepadqq/ ` everything is fine and Notepadqq starts just fine. If interested, I am happy to provide the code changes (very minor, only a few lines), build the AppImage and make it available here, appimage.org and my personal website.

**Comment by probonopd** [comment] 2017-01-01 01:54
Is the content of notepadqq_settings.zip read-only or read-write?

If it is read-only, then it should reside inside the AppImage and the application should load it from there.

If it is read-write for the user, then the application should copy it from inside the AppImage to `$HOME/.notepadqq/` if it is not there, so that the user does not have to download and manually unpack a zip file.

**Comment by skyide** [comment] 2017-01-01 02:52
Actually, notepadqq_settings.zip is a name of a file I made up for reference only. When installing notepadqq via the traditional `./configure` way, the script creates a dir called `share` in the `--prefix` dir  and in it there is another `dir` called `notepadqq` and this directory contains three folders: `editor`, `extension_tools` and `translations`. Take a look:

![screenshot](https://cloud.githubusercontent.com/assets/22862491/21579980/5f7eee32-d025-11e6-8719-604d9dc4c75b.png)

This is what I planned to pack `notepadqq_settings.zip` with because without `share/notepadqq/editor/index.html` notepadqq wouldn't run so it's a needed file. By default when you compile the original unmodified code and you turn it into an AppImage, as it is by default, the process seems to look for `share/notepadqq/editor/index.html` in `/tmp` which isn't right hence for my tweaking. Based on my brief code overview, there is a method called appDataPath() and it is that returns the path required so I just changed it to make it return `$HOME/.notepadqq` for consistency (and as an experiment to see how it would behave).

In relation to your question probonopd, I don't know whether those folders are read only or read/write as I only just started looking as I have some spare time but I agree, those files would need to be part of the AppImage and get copied to elsewhere if they are read/write. Depending on my spare time, I will update this post if I make further progress. I want to see what the path of the notepadqq executable would be within the AppImage as I need a point of reference so I would need to do some debugging (depending on my spare time).

**Comment by skyide** [comment] 2017-01-01 03:26
Ok I just added a debug statement that prints the path of the executable (in this case notepadqq-bin) and I recreated the AppImage and when you run the AppImage, I got `/tmp/.mount_4qZbiM` for the executable path from the debug statement and if you run it again and again the path is different every time. For instance, I ran it three times and I got: `tmp/.mount_88KwxE` and then I got `/tmp/.mount_jZ00nT`so everytime you run the AppImage, it extracts the contents of the AppImage to a different path in `/tmp`. Here is what is contained in the actual .mount dir in /tmp.

![screenshot](https://cloud.githubusercontent.com/assets/22862491/21580095/aca68596-d02d-11e6-88bc-0c298c9c09af.png)

Ok now I know what needs to happen, we just need to make that "share" folder part of the AppImage and get AppImage to extract in /tmp/.xyz and it would run just fine but this only makes sense if those files were read only (and I don't believe they are).

**Comment by skyide** [comment] 2017-01-01 05:06
Success! I just rebuilt it again and told `Notepadqq::appDataPath()` to look in the directory where the `notepadqq` binary is + `/share/notepad`and also rebuilt the AppImage and works like a charm Now the notepadqq-bin looks in its current directory for the `share` dir so every time the AppImage is run, the files get extracted in `/tmp` and the process starts. Here is a prove:

![screenshot](https://cloud.githubusercontent.com/assets/22862491/21580251/7f89e31a-d03b-11e6-9532-3a093aefdd4d.png)

This way however, you won't be able to permanently save translations because a fresh copy of the "share" dir along with everything else in the AppImage file is extracted to `/tmp`. Ok so as you can see, it's very doable and I have it running. Now the next thing to do is copy the contents of `/tmp/.mountxyz`'s share dir to $HOME and do some checking to see what exists and if the ones in $HOME exist use that else use the ones in /tmp and copy them to $HOME.

I can this going without a doubt.

**Comment by skyide** [comment] 2017-01-01 07:32
Ok all done. Notepaddqq.AppImage is ready for a release and here is a log of what happens when you launch it the first time and subsequent launches:

```
$ > ./Notepadqq.AppImage
Notepadqq::appDataPath(): Build type is BUILD_TYPE_APP_IMG
"Preparing a fresh copy of the local settings...cp -rf /tmp/.mount_VzPf8q/share/notepadqq/* /home/skyide/.notepadqq/"
Cool, we found local settings.

(Notepadqq.AppImage:22690): Gtk-WARNING **: Theme directory base/ of theme Oxygen-Mod-2 has no size field

Notepadqq::appDataPath(): Build type is BUILD_TYPE_APP_IMG
Cool, we found local settings.
Notepadqq::appDataPath(): Build type is BUILD_TYPE_APP_IMG
Cool, we found local settings.


$ > ./Notepadqq.AppImage
Notepadqq::appDataPath(): Build type is BUILD_TYPE_APP_IMG
Cool, we found local settings.

(Notepadqq.AppImage:22936): Gtk-WARNING **: Theme directory base/ of theme Oxygen-Mod-2 has no size field

Notepadqq::appDataPath(): Build type is BUILD_TYPE_APP_IMG
Cool, we found local settings.
Notepadqq::appDataPath(): Build type is BUILD_TYPE_APP_IMG
Cool, we found local settings.

I am just doing some final tweaks and I will posting a link to the download URL along with the code changes. I am also adding a small notice in the About dialog to indicate that this is an unofficial App Image build.

As you can see I've added a little setting in code to tell the compiler if we are compiling it for an AppImage or general. This way, my changes will compile with updated copies of the code.

**Comment by darealshinji** [comment] 2017-01-01 11:26
@skyide There is no need to modify the source code if you install the files so that the binary find everything it needs.

> This way however, you won't be able to permanently save translations because a fresh copy of the "share" dir along with everything else in the AppImage file is extracted to /tmp.

Shouldn't all the translations ship with the AppImage anyway?

Here's my recipe using pre-built Qt libraries to speed up building:
https://gist.github.com/darealshinji/86e06a433966b7663cf8377bde79670b

**Comment by skyide** [comment] 2017-01-02 00:01
I see, thx. WIth mine, I seem to have encountered an issue with linuxdeployqt which I wasn't aware before. I tested my AppImage with Linux Mint but I got lib errors:

![screenshot](https://cloud.githubusercontent.com/assets/22862491/21583530/c97c4a96-d0d9-11e6-81ef-e05dd949e177.png)

It appears that not all files went in to the AppImage and I will have to rebuild it again (the AppImage) and see how I go. I will check yours out when I have more time but I will need run it in a separate environment such as chroot or a virtualized environment. This is actually the first time I have ever touched this Notepadqq's code as well as building an actual AppImage.

**Comment by darealshinji** [comment] 2017-03-14 13:27
Any news on this?

**Comment by mischkl** [comment] 2017-07-10 10:01
@darealshinji could you perhaps post the newest already-built AppImage? Using Fedora here so I can't just run the script.

Thanks for your very welcome contribution!

**Comment by darealshinji** [comment] 2017-07-10 17:51
@mischkl I've uploaded it to the release section of my fork:
https://github.com/darealshinji/notepadqq/releases/tag/v1.0.1-51-g354f70d

**Comment by probonopd** [comment] 2017-07-10 17:52
How about upstreaming this?

**Comment by mischkl** [comment] 2017-07-11 09:00
Thanks a bunch @darealshinji!! Works awesome in Fedora 23!

**Comment by darealshinji** [comment] 2017-07-11 09:47
@probonopd What do you mean by "upstreaming"?

**Comment by probonopd** [comment] 2017-07-11 21:39
Making it part of the official notepadqq project @darealshinji

**Comment by darealshinji** [comment] 2017-07-13 09:11
Looks like it's working: https://github.com/darealshinji/notepadqq/releases/tag/continuous

@danieleds feel free to use `.travis.yml` and `build-appimage.sh` from my branch at https://github.com/darealshinji/notepadqq/tree/travis and modify them if you need.

**Comment by danieleds** [comment] 2017-07-13 23:18
Thank you! I have updated the repo and it seems to be working fine.

I'm closing this issue, but let me know if you notice something's weird or you just have some suggestions.

**Closed by danieleds** 2017-07-13 23:18 UTC

**Comment by probonopd** [comment] 2018-12-21 14:53
https://github.com/darealshinji/notepadqq/releases/tag/continuous gives 404 @darealshinji 

Where can the AppImage be downloaded from?

**Comment by darealshinji** [comment] 2018-12-21 18:34
Looks like I deleted the repo, lol. Should not be difficult to create an AppImage with qtlinuxdeploy.

**Comment by probonopd** [comment] 2018-12-21 19:10
Can you reinstate the repo? Many 3rd-party projects depend on it. Thanks!

**Comment by JuBan1** [comment] 2018-12-21 19:18
> Many 3rd-party projects depend on it

Which ones? Maybe they can switch over to snaps?

**Comment by probonopd** [comment] 2018-12-21 19:22
Sorry @JuBan1 I was referring to @darealshinji and his https://github.com/darealshinji/notepadqq/releases/tag/continuous repo.

I am only interested in AppImage since I am running various distributions from Live ISOs where Snappy is not an option for me @JuBan1

**Comment by darealshinji** [comment] 2018-12-21 20:07
Sorry, I already have too much stuff I need to look over. I think upstream should provide an official AI.

**Comment by JuBan1** [comment] 2018-12-22 09:42
I wouldn't be opposed to supporting it (again) but I doubt it'll happen during Daniel's hiatus.
