### ISSUE TITLE
Shift+Down to highlight a line, then copy+paste creates two endline chars

### ISSUE THREAD

**Issue by jazztickets** [notepadqq/notepadqq#859] opened 2019-03-20 20:26 UTC
**Describe the bug**
Using shift+down arrow key to highlight text produces weird behavior when copy and pasting.

**To Reproduce**
1. Place your cursor at the *beginning* of any line
2. Hold Shift, then press down arrow once to highlight the entire line.
3. Copy the line, then paste it somewhere
4. Pasting adds an additional endline character.

**Expected behavior**
Only the endline char copied should be pasted

**Screenshots**
![2019-03-20_14-24](https://user-images.githubusercontent.com/425930/54716700-f057d900-4b1b-11e9-8092-75b11c70e70c.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Distro package
 - Qt version: 5.12.2
 - Notepadqq version: 1.4.8

**Additional context**
Every other text editor i've used doesn't exhibit this behavior. I think it should be fixed.

**Comment by danieleds** [comment] 2019-08-30 16:27
Thanks for the precise report. This is expected behaviour, see for example vscode.

Closing for now, feel free to reopen in case you want to add more information or want to discuss whether this is the right behaviour.

**Closed by danieleds** 2019-08-30 16:27 UTC

**Comment by jazztickets** [comment] 2019-08-30 16:40
It's still wrong, but it's okay because i'll never use notepadqq. It shouldn't be pasting any extra endline characters. Try something besides vscode.

**Comment by danieleds** [comment] 2019-08-30 16:41
It would be useful if you provided some example of which text editor does that.

**Comment by danieleds** [comment] 2019-08-30 16:45
Sorry, I misunderstood your instruction.
It is not intended behavior but it has already been fixed in the master branch.
Thank you

**Comment by jazztickets** [comment] 2019-08-30 16:46
Thanks!
