### ISSUE TITLE
CTRL-C adds additional line (CTRL-Insert OK)

### ISSUE THREAD

**Issue by ThomasFinnern** [notepadqq/notepadqq#882] opened 2019-07-14 10:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report 
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a complete line is selected (Cursor on start of next line) and i press ctrl+c and insert it on a different place an empty line appears additionally

**Expected behavior**

I copied one line and want to insert one line exacly without aditionally ?lf?cr?
If i use ctrl+insert key it works as expected
 
**Minimal reproduction of the problem with instructions**

Line 1
Line 2
Line 3
Test 1
Test 2

Line two copied by ctrl-c with cursor before first character on Line 2 and line 3 each
The insert ctrl-v between lines Test 1 and Test 3 before first character in line Test 3 results in empty line additionally

Test 1
Line 2

Test 3

**Please tell us about your environment:**

Linux mint 19 (3.8.9), Qt version 5.11.3., Notepadqq v1.4.8

**Comment by danieleds** [comment] 2019-08-31 20:23
Thanks.

Duplicate of #859, fixed in master

**Closed by danieleds** 2019-08-31 20:23 UTC
