### ISSUE TITLE
Some weird hang ups when in markdown mode

### ISSUE THREAD

**Issue by gamer01** [notepadqq/notepadqq#653] opened 2018-05-03 13:22 UTC
It happens only in some documents and seems to be difficult to reproduce, so i have a document that seems to trigger the problem, but it also happened already with different documents. The bad type of bugs :D

**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Text area stops updating or even gets completely blank

**Minimal reproduction of the problem with instructions**
[protokoll.txt](https://github.com/notepadqq/notepadqq/files/1970989/protokoll.txt)
rename file to .md file-ending (github does not allow uploading .md files)
add and remove spaces before the `+` sign in the code in line 42
see yourself xD

**Please tell us about your environment:**
notepadqq 1.4.0, on archlinux

In this document the bug was extremely severe, but it also happens sometimes in other documents, but so far, i have the impression that it only appears when in markdown mode.

**Comment by danieleds** [comment] 2018-05-03 14:14
This doesn't seem to happen on the webengine2-promise branch (good sign). I still have to test it on master.

What version of Qt are you using?

(P.S. nice use of math mode! Also nice topics :P)

**Comment by danieleds** [comment] 2018-05-03 15:31
I'm not able to reproduce it. Can you provide more precise instructions? Also, I need these info:

 * type of package (Arch repos? Snap? source? ...)
 * any information printed to the console (start nqq from terminal)

**Comment by JuBan1** [comment] 2018-05-03 15:34
I can reproduce it with the current master, compiled from source.

FYI adding and removing the space in front of the `+` sign just once likely won't do it. Hammer the space and backspace keys and it happens after a second or two.

**Comment by danieleds** [comment] 2018-05-03 15:36
Ooooh nice, now I see it!

I confirm that the webengine branch seems to be immune.

**Comment by gamer01** [comment] 2018-05-04 11:58
For the meantime: Reopening the tab also solves the issue temporarily

**Comment by danieleds** [comment] 2019-09-04 20:17
Fixed in master

**Closed by danieleds** 2019-09-04 20:17 UTC
Labels: bug
