### ISSUE TITLE
App crashes when I accept "Use spaces" on open, if doc is in other view

### ISSUE THREAD

**Issue by petsam** [notepadqq/notepadqq#202] opened 2016-04-06 11:35 UTC
The situation is :

1. I open two files (xml). 
2. I get a message on the header for the document is using spaces to separate tabs with choices "Ignore" and "Use spaces". 
3. I choose "Use spaces" and the message goes away.
4. I then move one document to "Other view". 
5. The same message re-appears. 
6. If I choose "Ignore" it's OK.
7. If I choose "Use spaces" the program crashes.

I have a general setting to "Use tabs" for my own created docs, so, opening already formatted documents not having tabs for separation is temporary for me.

**Comment by danieleds** [comment] 2016-10-01 09:01
Is someone able to reproduce this on the master branch?

**Comment by Teklad** [comment] 2016-10-01 13:18
Not able to reproduce this on my end.  Its highly possible that this was either an upstream type issue or we accidentally fixed it at some point. :|

**Comment by danieleds** [comment] 2016-10-01 19:06
Hmm okay, I'm closing the issue then.

**Closed by danieleds** 2016-10-01 19:06 UTC
Labels: bug
