### ISSUE TITLE
"You are using an old version of Qt" shouldn't prompt to end-user

### ISSUE THREAD

**Issue by Explorer09** [notepadqq/notepadqq#397] opened 2017-03-14 06:10 UTC
I'm using Notepadqq the first time.
When I install Notepadqq on my Ubuntu and run it, it shows a "You are using an old version of Qt" message dialog.

This is a usability flaw that I should mention because:
1. Most users shouldn't care about Qt version when installing or running Notepadqq.
2. This is a packager's fault, not end-user's.  If a system doesn't provide the recent enough Qt version, either  the packager should supply with extension libraries (in a sub-package such as "notapadqq-qt"), or the Notepadqq version should be built with reduced features. Should be no need to warn end-user about this.
3. The Qt version check should be done silently, at compile time and on dynamic link time. Having a _runtime_ check _and a GUI dialog_ for it is bloat.

Related links about the same complaint:
* https://www.reddit.com/r/linuxmint/comments/3skasc/notepadqq_you_are_using_an_old_version_of_qt_521/
* https://superuser.com/questions/816987/installed-qt-5-3-notepadqq-still-finding-5-2-1-instead

Steps to reproduce:
1. Have Ubuntu 14.04.
2. Install Notepadqq from this PPA: https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq
Notepadqq version: 1.0.1-0~trusty1
3. Run Notepadqq.

Actual result:
A "You are using an old version of Qt (5.2.1)" dialog shows up. (There's a "Don't show me this warning again" checkbox. but the checkbox alone does not exempt the need to fix usability)

Expected result:
No such dialog should be shown up at all. (Reasons given above.)

**Comment by danieleds** [comment] 2017-03-14 10:26
This has been addressed in 26974581862f77f1bc6650a42858db22fc42e145.
Support for Qt 5.2 will be dropped in the next major release because it is too old and buggy.

**Closed by danieleds** 2017-03-14 10:26 UTC

**Comment by Explorer09** [comment] 2017-03-14 11:36
@danieleds 
What Qt 5.2 bugs were you trying to address? The point is Ubuntu 14.04 is still using Qt 5.2.1 by default. What was the reason that you dropped Qt 5.2 support?

Also, you should check the Qt version in the `configure` script.

**Comment by JuBan1** [comment] 2017-03-14 12:40
Notepadqq uses QtWebKit which has been deprecated for a while now. Its successor, QtWebEngine, is only available starting Qt 5.4 (and even in 5.4 support is still somewhat lacking).

Going forward Nqq will only support QtWebEngine and therefore requires at least Qt 5.4. Older versions keep running on QtWebKit but will probably only receive bugfixes. (At least I think that's the general consensus).

It's unfortunate for users on older distros buuut 14.04 is three years old by April and isn't even the latest Ubuntu LTS anymore.

I won't comment on the config script/packaging side of things because I don't know much about it but Nqq can use Qt versions other than your system install by placing them in `$HOME/Qt`. So Nqq doesn't have to determine during installation which Qt version to use.

Honestly, the whole version warning wasn't of much use I think. There was hardly any difference between the code paths for 5.2 and 5.3 and no real reason for the user to even be informed about.

**Comment by danieleds** [comment] 2017-03-14 23:30
The problem is that QtWebKit in Qt5.2 is full of bugs.
I agree that the message was not the best solution, however we expect to be able to ship "our" Qt with the next major version, and at that point the QtWebEngine-based Notepadqq will probably be available on Ubuntu 14.04 too.

**Comment by Explorer09** [comment] 2017-03-15 04:02
As long as you can make QtWebEngine work in Ubuntu 14.04, I wouldn't object that you drop support of QtWebKit.
