### ISSUE TITLE
Default indentation settings are not applied

### ISSUE THREAD

**Issue by eduardosm** [notepadqq/notepadqq#875] opened 2019-04-30 18:42 UTC
**Describe the bug**
Changing the default indentation settings to spaces does not have any effect.

**To Reproduce**
1. Go to 'Settings', 'Perferences', 'Languages'.
2. Select 'Default'.
3. Check 'Use spaces instead of tabs'.
4. Create a new file and press tab.

**Expected behavior**
A tab will appear instead of the chosen number of spaces. Additionally, 

**Environment (please complete the following information):**
 - OS: Manjaro Linux
 - Official Manjaro repository
 - Qt version 5.12.3
 - Notepadqq version 1.4.8

**Additional context**
Using fresh Notepadqq install. 'Default settings' is checked on 'Edit', 'Indentation'.

**Comment by ThaChillera** [comment] 2019-05-16 12:08
Additional:  

When opening a file with spaces, it notifies: "This file is indented with spaces, but your current settings specify to use tabs" With two buttons: "Use spaces" & "ignore".

Pressing "use spaces" replaces the spaces with tabs.

**Comment by drohm** [comment] 2019-07-24 20:11
I'm seeing the same behavior as well.  

Ubuntu Budgie 19.04
Flatpak installed, version 1.4.8

I've tested setting 'Default' and 'Text' to 'Use spaces instead of tabs' and when I open a .txt file, I still get the message at the top of the file that 'The file is indented with spaces, but your current settings specify to use tabs.'.

**Comment by kurdtpage** [comment] 2019-08-30 22:38
I have come across this as well, it seems there are two independent indentation settings:  
- Settings > Preferences > Languages  
- Edit > Indentation > Custom  

The latter option overrides the former option, so if you have custom settings set up, modifying the Preferences won't do anything.

**Comment by danieleds** [comment] 2019-08-31 10:43
This is probably a duplicate of #684, however what @kurdtpage is reporting is correct, if that's the problem in your case.

**Closed by danieleds** 2019-08-31 10:43 UTC

**Comment by danieleds** [comment] 2019-08-31 10:44
Also see here for a workaround: https://github.com/notepadqq/notepadqq/issues/886#issuecomment-522199515
