### ISSUE TITLE
[feature-request] Toolbar Customization

### ISSUE THREAD

**Issue by Cybermaxrus** [notepadqq/notepadqq#583] opened 2018-03-21 12:10 UTC
I would like to be able to add and remove buttons from the toolbar.
The customization window for me ideally looks in ms windows, but it is possible as in kde.
ms windows - http://www.dummies.com/wp-content/uploads/404532.image0.jpg
kde - https://patches.fedorapeople.org/fundamentals/toolbars-configure.png

**Comment by JuBan1** [comment] 2018-03-21 12:52
Dupe of #238

**Closed by JuBan1** 2018-03-21 12:52 UTC
