### ISSUE TITLE
Hide toolbar doesn't persist across sessions

### ISSUE THREAD

**Issue by Sagiri** [notepadqq/notepadqq#302] opened 2016-10-28 18:57 UTC
If you right click to hide the toolbar, and then close and restart notepadqq, it'll be visible again. There's no way to hide it in a persistent way.
##

**Comment by JuBan1** [comment] 2016-10-29 12:13
I just tried it and it works as intended for me. The toolbar stays hidden after closing and reopening the app.

If I recall correctly this is pretty much handled directly by Qt (through the `QMainWindow::restoreState()` function) so this might not be a bug on Nqq's end.

**Comment by Teklad** [comment] 2016-10-29 12:19
Upstream bugs between different QT versions tend to cause odd behavior across different distributions, unfortunately.  

I'm not against handling window restore state ourselves, but there's a few "odd" bugs that we can't fix without providing our own QT modifications, which would make maintenance quite a bit more cumbersome. #215 is a good example of this.

I don't really think this particular issue would need direct QT modifications, but its really a matter of maintain it ourselves or wait for QT and/or the distro to push the fixes.

**Comment by JuBan1** [comment] 2018-02-16 15:10
Closing due to no activity.

**Closed by JuBan1** 2018-02-16 15:10 UTC
