### ISSUE TITLE
Ctrl + F doesn't work with Qt 5.6

### ISSUE THREAD

**Issue by guekho64** [notepadqq/notepadqq#215] opened 2016-04-14 03:57 UTC
As the name says, Ctrl + F won't work at first glance. You need to use Ctrl + H to open "Find & Replace" and then change to the "Find" tab.

From there, you'll be able to use Ctrl + F like before.

Notepadqq v0.51.0 / amd64 / Qt 5.6.0 / Ubuntu 14.04 Trusty
##

**Comment by danieleds** [comment] 2016-04-14 07:25
It works for me.
What desktop environment are you using?
What language? (english?)

**Comment by xDShot** [comment] 2016-04-14 08:14
Same for me.

Arch x64, Xfce, notepadqq-git, Qt 5.6.0

**Comment by guekho64** [comment] 2016-04-14 08:47
DE: LXDE

Language: English

I suspect it has something to do with Qt, but I haven't tried with an older version (Like 5.5)

**Comment by excalibur1234** [comment] 2016-04-14 19:51
same for me.
it is funny, CTRL + H does not work for me, either.
but CTRL + SHIFT + F and then selecting the "find" tab works as a workaround.


arch 64bit, lxqt-git + kwin, notepadqq-git, qt5.6, language: german

**Comment by guekho64** [comment] 2016-04-14 20:06
CONFIRMED!

At least for me, Qt 5.5.1 it's working as it should. Guys, try to reproduce the bug using any older version than 5.6.0

Perhaps @excalibur1234 is right, and Qt 5.6.0 broke the Keyboard Shorcuts...

**Comment by alvisc** [comment] 2016-05-27 06:52
Gentoo, since update of Qt 5.6.0 from Qt 5.4.x need to press Ctrl +H, or Ctrl + Shift +F for search dialog.
Ctrl + F works until restart.
Tested on notepadqq v0.50.4 and v0.51.0 from git.

**Comment by guekho64** [comment] 2016-05-27 07:01
Use Qt 5.5.1, it's the latest version of QT without this type of issue.

@excalibur1234 said something about Qt 5.6.x issues with keyboard shortcuts...

**Comment by rotanid** [comment] 2016-05-31 13:21
can also confirm this boing, quite annoying...

arch 64bit, XFCE, notepadqq 0.51.0-2, qt 5.6

**Comment by dagostinelli** [comment] 2016-06-27 15:35
I can confirm that this is still broken as of this posting date.  I reinstalled Fedora Linux a few days ago.  Then 1 hour ago cloned latest, compiled, make install, launched, opened a file and pressed Ctrl+F.  Did not work.  

Fedora: 4.5.7-300.fc24.x86_64
QT 5.6.0
notepadqq: 0.51.0

**Comment by danieleds** [comment] 2016-08-12 09:21
Confirmed for me too, with Qt 5.6.0 and notepadqq 0.52.1.

**Comment by rotanid** [comment] 2016-08-12 14:40
no problems at the moment running Qt 5.7.0 and notepadqq 0.52.1.

**Comment by excalibur1234** [comment] 2016-08-12 21:15
i also use qt5.7.0 now and keyboard shortcuts seem to work, including CTRL+F

**Comment by danieleds** [comment] 2019-10-02 16:28
Closing since this seems to be an upstream bug in Qt and it is related to the now very old version 5.6.

**Closed by danieleds** 2019-10-02 16:28 UTC
Labels: bug
