### ISSUE TITLE
QtWebEngine: deployment considerations

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#381] opened 2017-03-08 21:00 UTC
Which distributions ship QtWebEngine?
Can we ship it ourselves?
Etc.

**Comment by Teklad** [comment] 2017-03-08 21:02
For distros that don't support it... we should probably link here:
https://wiki.qt.io/How_to_Try_QtWebEngine

**Comment by Teklad** [comment] 2017-03-08 21:08
We could probably check for QTWebEngine in our script and build it 
ourselves in the event it doesn't exist... but this is a lot of QMake 
magic that I'm not at all familiar with... so I wouldn't have the 
slightest clue on how to do that.

**Comment by JuBan1** [comment] 2017-03-08 21:09
Minimum supported version for WebEngine is Qt 5.4 so that's the minimum we can target. 

Unfortunately some useful functionality was added in the later versions so things get a bit tricky. Ubuntu LTS is at Qt 5.5 so that would be a nice minimum as well. Then again, QWebEngine is only included in 17.4 and onwards..

**Comment by danieleds** [comment] 2017-03-08 21:09
I'm actually thinking more about distros like ubuntu for which we have to provide precompiled packages compatible with the available packages within the main repos.

**Comment by Teklad** [comment] 2017-03-08 21:11
Pre-compiled you say?  Now that's an idea... that would save us from a 
lot of headache questions like:
"How do I compile this blasted contraption?"

Should we provide it alongside notepadqq as an extra package if they 
need it then?

**Comment by Teklad** [comment] 2017-03-08 21:14
Print support just won't be available for a while unless we can find a way to do it via QWidget::render.... but like I said rendering is done in a very odd manner in QWebEngineView so making that work is going to be extremely difficult even with internal knowledge of how it works.

**Comment by Teklad** [comment] 2017-03-08 21:17
Or maybe not... I should really just try it and see at some point... but I need to do more bug squashing first. :)... @JuBan1 .... wanna take a crack at printing?  It might not be too bad.

**Comment by Teklad** [comment] 2017-03-08 21:18
I'm getting way off-topic... sorry... but yea... if we just provide a package that users can download alongside Notepadqq, I think that would be our best bet.

**Comment by danieleds** [comment] 2017-03-08 21:24
Another off-topic: my laptop just committed hardware suicide. I expect to be a little bit less connected in the next few days.

**Comment by Teklad** [comment] 2017-03-08 21:25
A constant reminder of why I build my own desktops and think laptops are 
evil. :p

**Comment by JuBan1** [comment] 2017-03-08 21:34
> wanna take a crack at printing?

Good news: printing is disabled even in the current version so it's not a necessity to implement it for WebEngine to get feature parity with Webkit. Never used it so I didn't even know that.

Still, I can take a crack at it. Wouldn't be surprised if I can just render to a canvas and print that.

**Comment by Teklad** [comment] 2017-03-08 21:37
Would using a "Loading..." QLabel in place of the webview until its ready to render be acceptable?  That white flash is giving me migraines.

**Comment by JuBan1** [comment] 2017-03-08 21:46
> Would using a "Loading..." QLabel in place of the webview until its ready to render be acceptable? That white flash is giving me migraines.

IMO just display an empty panel. Loading a page is a fraction of a second unless in exceptional situations (like the file being located on a sleeping HDD that has to spin up first).

**Comment by danieleds** [comment] 2017-03-09 21:09
Back to in-topic.
This PPA contains a prebuilt binary of qtwebengine: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt58-trusty
We might be able to use it within our PPA.

**Comment by ihnorton** [comment] 2017-07-08 03:49
Not sure if this is the correct place to mention this, but: the qwebengine-beta branch built easily against Qt 5.8 from homebrew (`PATH=/usr/local/Cellar/qt/5.8.0_2/bin/:$PATH ./configure -d`). It segfaulted first, which I fixed with a [tiny patch](https://gist.github.com/ihnorton/200c6ebe689e00fb26da1365bb094a08). After that, starts fine and basic functions seem ok (had some crashes when doing replace-all).

**Comment by JuBan1** [comment] 2017-07-08 16:44
@ihnorton That's probably one of the previously blocking functions now being unblocking. Thanks for the info. At the moment it doesn't look like we're going to continue work on the WebEngine branch but I'll keep that in mind if we decide to pick it up again.

**Comment by ihnorton** [comment] 2017-07-08 17:48
@juban1 interesting. if I may, what is replacing qwebkit now, and is there any discussion about why/downside/issues/etc.? I wasn't actually looking for an editor (though it is nice!), but evaluating webengine and looking at any usage I can find.

**Comment by JuBan1** [comment] 2017-07-08 18:44
@ihnorton #432 WebEngine's brought a lot of headache dealing with its quirks, and WebKit is the cause of some bugs too that we pretty much can't fix without forking WebKit. So we were looking at replacing it with a "proper" editor widget.

**Comment by Teklad** [comment] 2017-07-09 00:05
To touch on that... Time constraints unfortunately keep a lot of us developers from finishing projects in the amount of time we would like.  It's been a couple of months since I've had time to poke at notepadqq due to real life issues.

As soon as I manage to get some more free time I'll get back to working on the widget.  Unfortunately the ETA on that is unknown... such is the way of open source. :p

**Closed** 2018-03-20 21:04 UTC
