### ISSUE TITLE
UI Main Menu Bar not drawn after new files are opened and path is displayed when External Programs launch Notepadqq

### ISSUE THREAD

**Issue by NeoBeum** [notepadqq/notepadqq#445] opened 2017-05-12 13:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report

```

**Current behavior**

UI Main Menu Bar not drawn after new files are opened and path is displayed when External Programs launch Notepadqq or call Notepadqq to open the file

**Expected behavior**

UI Menu draws

**Minimal reproduction of the problem with instructions**

[http://i.imgur.com/YVeOLGN.png](url)  These links aren't working for some reason
[http://i.imgur.com/JJdU4Mn.png](url)

i.imgur.com/YVeOLGN.png
i.imgur.com/JJdU4Mn.png

**Please tell us about your environment:**

Ubuntu 16.10 64-bit
Gallium 0.4 on llvmpipe (LLVM 3.8, 256 bits)
Intel® Core™ i7-4870HQ CPU @ 2.50GHz × 4 
15.7 GiB

**Comment by JuBan1** [comment] 2017-05-12 13:39
Probably duplicate of #409

**Comment by NeoBeum** [comment] 2017-05-12 15:56
Have this too for more investigation
http://i.imgur.com/nNBdAm7.png
[Imgur](http://i.imgur.com/nNBdAm7.png)

**Comment by JuBan1** [comment] 2018-04-29 07:16
I think this *should* have been fixed a while ago with changes to how we handle the Unity environment. If it still happens feel free to comment or open a new issue.

**Closed by JuBan1** 2018-04-29 07:16 UTC
