### ISSUE TITLE
Spaces/tabs indentation settings are not respected

### ISSUE THREAD

**Issue by ckp95** [notepadqq/notepadqq#886] opened 2019-08-06 21:03 UTC
**Describe the bug**
I tell Notepadqq to use spaces instead of tabs for my chosen language. It doesn't actually do so.

**To Reproduce**
- Set Language to e.g. Python (this happens for any language, just using it as an example).
- Go to Settings -> Preferences -> Languages
- Choose "Python" from dropdown
- Uncheck "Use default settings", check "Use spaces instead of tabs"
- Click apply, then okay
- Type something that uses indentation and check "show all characters" in the toolbar to see the kind of whitespace inserted

**Expected behavior**
Indentation should use spaces instead of tabs.

**Screenshots**
https://imgur.com/6S3dJ4q.png

**Environment (please complete the following information):**
 - OS: Manjaro Linux
 - Installation type: from Manjaro community repository
 - Qt version 5.13.0
 - Notepadqq version v1.4.8

**Additional context**

**Comment by kenjican** [comment] 2019-08-17 03:13
I have exactly same issue,it's really annoying. This is my solution, it works.

The preferences is stored in Notepadqq.ini . In my computer this file resides here: ~/snap/notepadqq/current/.config/Notepadqq

edit this file and replace all the three setting:

UseDefaultSettings=false - > UseDefaultSettings=true
IndentWithSpaces=false -> IndentWithSpaces=true
TabSize=4  -> TabSize=2

or just those languages that you prefer.

OS: Mint 19.1 tessa
notepad : v1.4.2

**Comment by danieleds** [comment] 2019-08-30 16:20
Duplicate of #684 .

This has been fixed and will be available in the next release.

**Closed by danieleds** 2019-08-30 16:20 UTC
