### ISSUE TITLE
Disable warning "The file is indented with spaces, but your current settings specify to use tabs"

### ISSUE THREAD

**Issue by NeuroNex** [notepadqq/notepadqq#537] opened 2018-01-27 23:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Each time I open a file, there is a warning in a blue bar on top
**The file is indented with spaces, but your current settings specify to use tabs**

I go to Settings / Preferences / General:
UNCHECK "Warn when the indentation doesn't match the settings"

Close NPqq, reopen the same file. Same warning appears. Go back to Settings / Preferences
The option is still checked. Meaning the app didn't acknowledged the setting change made previously.

**Expected behavior**

- Must honnor the setting made by the user
Or, in the blue bar top setting, beside de "Use Space" and "Ignore" buttons, add a checkbox "User this rule permanently"

**Minimal reproduction of the problem with instructions**

Save a file with a few lines
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
(type space 3 times)bbbbbbbbbbb
(type space 3 times)bbbbbbbbbbb

Save the file as NotepaddqqMessedUpTabs.txt
Reopen the file again and you will see that blue bar warning on the top

**Please tell us about your environment:**

LinuxMint 18.3
Qt 5.5.1
Notepadqq 1.20

**Comment by danieleds** [comment] 2018-03-12 10:08
Closing: not confirmed and likely a problem with config file permissions

**Closed by danieleds** 2018-03-12 10:08 UTC

**Comment by JBrakefield** [comment] 2019-04-30 19:16
I don't see a fix for this, so why is this issue closed? If it is a problem with the config, please say how to fix.

**Comment by JuBan1** [comment] 2019-04-30 20:55
Do you have the same issue that the `Warn when the indentation doesn't match the settings` doesn't stay unchecked?

I tested it on the current master branch and it seems to work fine. The option stays unchecked and I don't get warning dialogs.

**Comment by JBrakefield** [comment] 2019-04-30 22:11
I didn't see that option before, thank you. I have another issue where my terminal outputs "Missing icon:" blah blah a dozen times, EVERY time I open the program, so I might just have to switch to something else. Again. Can't seem to find a good reliable text editor to use in my WLS Ubuntu 16.04.

**Comment by JuBan1** [comment] 2019-04-30 22:17
https://github.com/notepadqq/notepadqq/pull/774 ought to fix that I think, though it's stuck in limbo.

**Comment by baigudin** [comment] 2021-10-03 17:14
Notepadqq 1.4.2 - the issue appeared after the first installation on Ubuntu 18.04. So, that great approach to close the issue just because you can't confirm it. No conformation for 3 years... Confirm the issue exists, just try to install Ubuntu from scratch and after that install your Notepadqq. 
P.S. As an user I wouldn't like to go to any config files and change access permissions. I would just use it from the box.
