### ISSUE TITLE
get no menu line

### ISSUE THREAD

**Issue by frank-github** [notepadqq/notepadqq#150] opened 2015-09-21 22:32 UTC
just installed notepadqq
I got no menu line, only icon line
using qt 5.2.1, but don't want to update to > 5.3, because it's not in distribution of ubuntu 14.4

how can I get menu line?
only if I use qt > 5.3 ?
##

**Comment by frank-github** [comment] 2015-09-21 22:38
![Uploading notepadqq-without-menue.png…]()

**Comment by danieleds** [comment] 2015-09-22 08:21
Strange, can someone confirm on the same setup?

**Comment by frank-github** [comment] 2015-09-22 09:06
Hi, can I check anything on my system? Any logging? Or activate trace options for more informations?

**Comment by frank-github** [comment] 2015-10-07 22:12
I got the same issue with another tool qpdfview, after installing a newer version.
With the developer I found "my" problem, something with qt v5 is wrong :-(
He downgrade his tool back to qt v4 and everything is fine again :-)

Do you know a way to upgrade to qt > 5.3, without downloading this big complete suite (500 MiB)

**Comment by danieleds** [comment] 2015-10-08 13:07
No, no way... :(
But it isn't normal anyway. With Qt 5.2.1 you must have the menu bar. Maybe something has gone wrong with your Qt packages? Can you try reinstalling it?

Are you sure it isn't a "global menu" issue? Have you tried to disable it?

**Comment by frank-github** [comment] 2015-10-08 18:48
Hi, I didn't install Qt 5.2.1 myself, must be included by ubuntu 14.4 or as dependency of any other tool I installed.
I did reinstall all packages qt 5.* now, but didn't change anything

What do you mean "global menu" issue? How can I try to disable menu?
I installed notepadqq, started it initially, no menu was shown

**Comment by Teklad** [comment] 2016-09-08 20:46
This was a bug in upstream QT.  We now require QT 5.3 at the very least.  I think this can be closed as well. :)

**Comment by CrltnG** [comment] 2016-10-14 22:57
I get no menu line either, have just spent the past few hours trying to make Notepadqq work. Can't find documentation on how to run without the menu.
Installed Qt 5.7, QT Creator shows it, but running **qmake --version** in the command line fails.  Would appreciate if you would notify users that Notepadqq isn't really a complete program, it's more like a bundle of great scripts, but can't really run or be installed on it's own.
I'm trying to represent Linux at my college, am taking two programming classes: JavaScript and Java. In my JavaScript class there are about 18 people, I am the only one using Linux. In the Java class, about 46 people, only 4 of us use Linux.
Whatever the case, perhaps before adding kool new features; you should make it where it can be installed simply by running sudo apt-get install notepadqq.  Instead of making the user go figure out what they must add and configure in order to get your software to run.
boohoo

**Comment by Teklad** [comment] 2016-10-14 23:01
Having notepadqq in the repository is up to the distribution of choice.  
Since you're using a Debian-based distribution of Linux, you should be 
able to run the following commands to get notepadqq installed:

sudo add-apt-repository ppa:notepadqq-team/notepadqq
sudo apt-get update
sudo apt-get install notepadqq


This will install the latest release version of notepadqq.  Also, in 
order to compile notepadqq from source, you would have to run the 
following instead:

./configure

make

sudo make install


I hope this helps.  If you have any further questions, please feel free 
to ask.

**Comment by flymikeG** [comment] 2017-06-19 21:07
I also have no Menu line - but only when notepadqq is launched via Open With from Files/Nautilus. The menu does appear when launched from the Unity Launcher.
My Settings/Appearance/Behavior is "Show the menus for a window in the window's title bar" and Menus Visibility is "Always displayed".
Notepadqq is the only app I see this problem with.

Ubuntu 16.04.2 LTS, Notepadqq 1.0.1, Qt 5.5.1

**Comment by michaeldrouin** [comment] 2017-12-29 01:49
as @flymikeG said, the issue is as soon as a file is opened through a file browser such as Nautilus, the menu bar goes away. if files are opened through the context menus or drag-and-dropped into notepadqq, everything stays fine and the menu will continue to appear. also, when notepadqq is first opened via opening a file through nautilus, the menu is there until a second file is opened through nautilus

**Comment by michaeldrouin** [comment] 2018-03-14 22:31
are there any plans of resolving this?
ubuntu 16.04.3 LTS, Notepadqq 1.2.0, Qt 5.5.1

**Comment by JuBan1** [comment] 2018-03-14 22:45
I've looked into it before but it's hard to diagnose an issue I can't recreate with a fresh installation.

Could you answer these questions please: 

What desktop shell are you using? Unity, Gnome?

Do you get an output if you run `env | grep QT_QPA` in the console?

**Comment by michaeldrouin** [comment] 2018-03-14 22:53
to add onto this, if it helps with debugging, once another file is opened, the notepadqq window shifts to a different position on the screen.

**Comment by michaeldrouin** [comment] 2018-03-14 23:17
attached are some pictures showing the issues. you can't see the mouse cursor in the screenshot, but all 4 were with the mouse hovering over the title bar. the before pictures are when notepadqq is first opened. once another file is opened, say through nautilis. that menu that appeears when you hover over  the titlebar with the mouse no longer appears. however, in both the snap and apt packages, dragging a file into notepadqq to open does NOT make this menu disappear. 

also of note, the menus are a lot different. note the snap-menu file. the only options in the 'settings' menu in the apt package is 'preferences'. there is no option to show menubar. in the apt package, pressing CTRL-M does not make it appear either. both installs show a version of 1.2.0 with a qt version of 5.5.1, so i'm not sure why there's a difference.

![apt-after](https://user-images.githubusercontent.com/7315656/37435924-a9127bd8-27a2-11e8-8476-29c0fc6d143b.png)
![apt-before](https://user-images.githubusercontent.com/7315656/37435925-a93077d2-27a2-11e8-861e-ff673f21bd1b.png)
![snap-after](https://user-images.githubusercontent.com/7315656/37435926-a9478062-27a2-11e8-85d7-5191136ba470.png)
![snap-before](https://user-images.githubusercontent.com/7315656/37435927-a961cfe4-27a2-11e8-9ebd-0bf839809a1f.png)
![snap-menu](https://user-images.githubusercontent.com/7315656/37435928-a97aca12-27a2-11e8-9229-bdaf2f1647bc.png)

**Comment by JuBan1** [comment] 2018-03-14 23:53
Okay, those details were helpful. I've got an assumption of what the problem is. The short story is that there's a tool called `appmenu-qt5` that Unity uses to grab a program's menu bar and show it in the titlebar instead. When opening a document through Nautilus it'll basically do the commandline equivalent of `notepadqq /path/to/file.txt`, but since an instance of Notepadqq is already running, this new Notepadqq instance will simply pass the file path to the existing one and close itself again. I assume this confuses `appmenu-qt5` into thinking that Notepadqq shut down entirely, and therefore it's not helping Unity in showing the titlebar menu anymore.

I think this won't happen with Ubuntu 16.10 and newer anymore, since they've stopped using `appmenu-qt5` from that point on.

As far as I can gather, running Nqq with `QT_QPA_PLATFORMTHEME="" notepadqq` should prevent `appmenu-qt5` from taking over. You should see the normal menu and no titlebar menu. Can you confirm this?

Tomorrow I'll see if I can reproduce the scenario. If the fix works perhaps we'll just have to unset `QT_QPA_PLATFORMTHEME` for Ubuntu 16.04 and lower. It breaks the titlebar menu but at least you'll *get* a menu.

> the menus are a lot different. note the snap-menu file. 

That's as expected. The snap package is continuously updated while the apt package only gets updated every now and then. The version number is misleading unfortunately.

**Comment by michaeldrouin** [comment] 2018-03-15 00:21
> As far as I can gather, running Nqq with `QT_QPA_PLATFORMTHEME="" notepadqq` should prevent appmenu-qt5 from taking over. You should see the normal menu and no titlebar menu. Can you confirm this?

you are correct. the normal menu appears with no titlebar hover menu. opening a document through nautilus still causes the window to jump around (which i don't personally have an issue with), but there is still at least a menu.

**Comment by danieleds** [comment] 2018-03-15 00:50
Just to add something to the excellent explanation by JuBan1, I can tell you that beginning from the next release the version numbers will be in line again in both repositories.

What happened is that we inherited the snap package from an unofficial source that was deploying a prerelease version of the application. When I got the ownership of that package, in order to avoid downgrading the app for all the snap users, I decided to keep it like that and re-align them in the following update.

Sorry for the confusion

**Comment by michaeldrouin** [comment] 2018-03-15 17:30
JuBan1's response was amazing. very detailed and clear on what the issue was and what the workarounds are and what the future is. thank you very much. 

and no problem at all with the confusion on version numbers. i've unfortunately dealt with similiar issues myself more times than i'd like to admit. 

thank you both so much for the responses and all the work put into such a great program.

**Comment by JuBan1** [comment] 2018-03-15 21:50
Should be fixed by #578 by preventing `appmenu-qt5` from doing its magic.

**Closed** 2018-03-15 21:51 UTC
Labels: bug
